
	//var btnAll = document.getElementById("btn-all");
	var btnPools 		=		document.getElementById("btn-pools");
	var btnCottages 	=		document.getElementById("btn-cottages");
	var btnFoods 		=		document.getElementById("btn-foods");
	var btnRooms 		=		document.getElementById("btn-rooms");
	var btnActivities 	=		document.getElementById("btn-activities");

	var displayPools 		= 	document.getElementById('row-1');
	var displayCottages 	= 	document.getElementById("row-2");
	var displayFoods 		= 	document.getElementById("row-3");
	var displayRooms 		= 	document.getElementById("row-4");
	var displayActivities 	= 	document.getElementById("row-5");

	/*btnAll.onclick = function(){
		displayCottages.style.display = "block";
		displayFoods.style.display = "block";
		displayRooms.style.display = "block";
		displayPools.style.display = "block";
		displayActivities.style.display = "block";
	}*/

	btnPools.onclick = function(){
		displayPools.style.display = "block";
		displayCottages.style.display = "none";
		displayFoods.style.display = "none";
		displayRooms.style.display = "none";
		displayActivities.style.display = "none";
        btnPools.style.background = "#fc3187";
        btnPools.style.color = "#fff";
        btnPools.style.border = "solid 1px #fc3187";
        btnCottages.style.background = "#fff";
        btnCottages.style.color = "#fc3187";
        btnCottages.style.border = "solid 1px #fc3187";
        btnFoods.style.background = "#fff";
        btnFoods.style.color = "#fc3187";
        btnFoods.style.border = "solid 1px #fc3187";
        btnRooms.style.background = "#fff";
        btnRooms.style.color = "#fc3187";
        btnRooms.style.border = "solid 1px #fc3187";
        btnActivities.style.background = "#fff";
        btnActivities.style.color = "#fc3187";
        btnActivities.style.border = "solid 1px #fc3187";
	}
	
	btnCottages.onclick = function(){
		displayPools.style.display = "none";
		displayCottages.style.display = "block";
		displayFoods.style.display = "none";
		displayRooms.style.display = "none";
		displayActivities.style.display = "none";
        btnCottages.style.background = "#fc3187";
        btnCottages.style.color = "#fff";
        btnCottages.style.border = "solid 1px #fc3187";
        btnPools.style.background = "#fff";
        btnPools.style.color = "#fc3187";
        btnPools.style.border = "solid 1px #fc3187";
        btnFoods.style.color = "#fc3187";
        btnFoods.style.border = "solid 1px #fc3187";
        btnFoods.style.background = "#fff";
        btnRooms.style.background = "#fff";
        btnRooms.style.color = "#fc3187";
        btnRooms.style.border = "solid 1px #fc3187";
        btnActivities.style.background = "#fff";
        btnActivities.style.color = "#fc3187";
        btnActivities.style.border = "solid 1px #fc3187";
    }
	btnFoods.onclick = function(){
		displayPools.style.display = "none";
		displayCottages.style.display = "none";
		displayFoods.style.display = "block";
		displayRooms.style.display = "none";
		displayActivities.style.display = "none";
        btnFoods.style.background = "#fc3187";
        btnFoods.style.color = "#fff";
        btnFoods.style.border = "solid 1px #fc3187";
        btnPools.style.background = "#fff";
        btnPools.style.color = "#fc3187";
        btnPools.style.border = "solid 1px #fc3187";
        btnCottages.style.background = "#fff";
        btnCottages.style.color = "#fc3187";
        btnCottages.style.border = "solid 1px #fc3187";
        btnRooms.style.background = "#fff";
        btnRooms.style.color = "#fc3187";
        btnRooms.style.border = "solid 1px #fc3187";
        btnActivities.style.background = "#fff";
        btnActivities.style.color = "#fc3187";
        btnActivities.style.border = "solid 1px #fc3187";
	}
	btnRooms.onclick = function(){
		displayPools.style.display = "none";
		displayCottages.style.display = "none";
		displayFoods.style.display = "none";
		displayRooms.style.display = "block";
		displayActivities.style.display = "none";
        btnFoods.style.background = "#fff";
        btnFoods.style.color = "#fc3187";
        btnFoods.style.border = "solid 1px #fc3187";
        btnPools.style.background = "#fff";
        btnPools.style.color = "#fc3187";
        btnPools.style.border = "solid 1px #fc3187";
        btnCottages.style.background = "#fff";
        btnCottages.style.color = "#fc3187";
        btnCottages.style.border = "solid 1px #fc3187";
        btnRooms.style.background = "#fc3187";
        btnRooms.style.color = "#fff";
        btnRooms.style.border = "solid 1px #fc3187";
        btnActivities.style.background = "#fff";
        btnActivities.style.color = "#fc3187";
        btnActivities.style.border = "solid 1px #fc3187";
	}
	btnActivities.onclick = function(){
		displayPools.style.display = "none";
		displayCottages.style.display = "none";
		displayFoods.style.display = "none";
		displayRooms.style.display = "none";
		displayActivities.style.display = "block";
        btnFoods.style.background = "#fff";
        btnFoods.style.color = "#fc3187";
        btnFoods.style.border = "solid 1px #fc3187";
        btnPools.style.background = "#fff";
        btnPools.style.color = "#fc3187";
        btnPools.style.border = "solid 1px #fc3187";
        btnCottages.style.background = "#fff";
        btnCottages.style.color = "#fc3187";
        btnCottages.style.border = "solid 1px #fc3187";
        btnRooms.style.background = "#fff";
        btnRooms.style.color = "#fc3187";
        btnRooms.style.border = "solid 1px #fc3187";
        btnActivities.style.background = "#fc3187";
        btnActivities.style.color = "#fff";
        btnActivities.style.border = "solid 1px #fc3187";
	}